version: "3"

services:
  todo:
    container_name: "todo_server"
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/todos_dev
    depends_on:
      - db
    ports:
      - 7000:7000
  db:
    container_name: "todo_db"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos_dev
